name: Publish to FastMinecraft/maven-repo

on:
    workflow_dispatch:

jobs:
    call-workflow:
        uses: FastMinecraft/maven-repo/.github/workflows/MavenPublishNew.yml@main
        with:
            target-owner: FastMinecraft
            target-repo: maven-repo
            target-branch: repo
        secrets:
            token: ${{ secrets.MAVEN_REPO_GIT }}
